### ISSUE TITLE
Search results corrupted?

### ISSUE THREAD

**Issue by jojojames** [Wilfred/deadgrep#10]
<img width="1552" alt="screenshot 2018-07-11 18 35 49" src="https://user-images.githubusercontent.com/1227856/42607752-54886024-8539-11e8-9434-f3a318a349de.png">

Any thoughts on how to debug this?

**Comment by Wilfred** [comment]
Weird! What version of ripgrep are you using, and on what platform?

**Comment by jojojames** [comment]
~/ $ rg --version
ripgrep 0.7.1
-AVX -SIMD

OSX, Sierra

**Comment by Wilfred** [comment]
It looks like ripgrep 0.8.0 changed the colour codes: https://github.com/BurntSushi/ripgrep/blob/master/CHANGELOG.md and deadgrep depends on them. Could you try upgrading your ripgrep version?

**Comment by jojojames** [comment]
Thanks, that was it.
