### ISSUE TITLE
[Feature Request] Add option to extend search to ignored files

### ISSUE THREAD

**Issue by ktetzlaff** [Wilfred/deadgrep#100]
Most of the time, the automatic evaluation of ignore files makes a lot of sense. However, sometimes it is necessary to expand the search to otherwise ignored files. For those cases `ripgrep` offers the `--unrestricted` option (which has three different levels to include ignored files equivalent to `--no-ignore` `--hidden` and `--binary`):

       •   -u is equivalent to --no-ignore
       •   -uu is equivalent to --no-ignore --hidden
       •   -uuu is equivalent to --no-ignore --hidden --binary

It would be nice to be able to configure this via the `deadgrep` search buffer. Either via dedicated config 'items' or, maybe more flexible, by allowing the user to specify additional command line options which `deadgrep` then just adds to the `ripgrep` command line.

The latter would allow to also add e.g.:

       •   -L/--follow will force ripgrep to follow symlinks

and thus include the content of the link target in the search (instead of ignoring it).

**Comment by bestlem** [comment]
See PR#95 - my minimal use seems to show it works
