### ISSUE TITLE
Searching `a{` by regexp results in a blank buffer: deadgrep--propertize-regexp: Args out of range: 1, 3

### ISSUE THREAD

**Issue by jdufresne** [Wilfred/deadgrep#103]
steps to reproduce:

1. Run `deadgrep` command
2. Type text `a{`
3. Hit Enter
4. On the next screen change "Search type" to "regexp"

Actual result: a blank buffer

Expected result: Some kind of user facing error that `a{` is invalid regexp syntax. I can't even switch back to search type "string". For example:

```
$ rg 'a{'
regex parse error:
    a{
     ^
error: unclosed counted repetition
```

In the `*Messages*` buffer, I see

```
deadgrep--propertize-regexp: Args out of range: 1, 3
```

I bump into this from time to time when typing too fast and miss a key.

---

`M-x deadgrep-debug` 

```
About your environment:
Platform: gnu/linux
Emacs version: 27.2
Command: rg --color=ansi --line-number --no-heading --no-column --with-filename --fixed-strings --smart-case -- a{ .
default-directory: "~/"

Initial output from ripgrep:
nil
```

```
$ rg --version
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

**Comment by Wilfred** [comment]
Should be fixed now :)

**Comment by jdufresne** [comment]
Thank you for the quick fix! :slightly_smiling_face:
