### ISSUE TITLE
project-roots is obsolote 

### ISSUE THREAD

**Issue by sje30** [Wilfred/deadgrep#108]
https://github.com/Wilfred/deadgrep/blob/aebaf72e35546fd235b4861399791814e4e4c7d8/deadgrep.el#L1448

the docstring for project-roots says to use project-root now.

**Comment by AtomicNess123** [comment]
Here having the same problem when installing:
```
In end of data:
deadgrep.el:1603:1:Warning: the function `project-roots' is not known to be
    defined.
```

**Comment by alanz** [comment]
It is bundled with emacs.  For me it is at `.../share/emacs/27.2/lisp/progmodes/project.el`
