### ISSUE TITLE
Re-use existing `*deadgrep ...*` buffer

### ISSUE THREAD

**Issue by fleimgruber** [Wilfred/deadgrep#121]
I was trying to implement https://www.masteringemacs.org/article/demystifying-emacs-window-manager#example-2-reusing-windows for deadgrep buffers, i.e. to have them re-use any existing window that already displays a `*deadgrep ...*` buffer. I tried with:

```emacs-lisp
(add-to-list 'display-buffer-alist
             `(,(rx (| "*xref*"
                       "*grep*"
                       "*Occur*"
                       (and "*deadgrep" (* not-newline) "*")))
               display-buffer-reuse-window
               (inhibit-same-window . nil)))
```

which *should* do what I want. It does not work though and this motivates the actual question: does deadgrep do something special that prevents this config from having the desired effect? Or is there a setting in deadgrep already to re-use windows (could not find it in docs and quick code search)? Also, I am setting `(setq switch-to-buffer-obey-display-actions t)` so the default of `deadgrep-display-buffer-function` being `switch-to-buffer-other-window` should respect the `display-buffer-alist` setting in the above snippet.

**Comment by Singletoned** [comment]
I'm trying to solve the same underlying problem (get deadgrep to reuse buffers) so I'd be keen to hear of any solutions or alternatives

**Comment by Wilfred** [comment]
Hmm, I think these are two unrelated issues actually. Reusing buffers is a reasonable feature addition, but the window question might be a bug.

**Comment by firstrow** [comment]
this might help

```

(defcustom deadgrep-max-buffers
  4
  "The maximum number of deadgrep results buffers.

If the number of results buffers exceeds this value, deadgrep
will kill results buffers. The least recently used buffers are
killed first.

To disable cleanup entirely, set this variable to nil."
  :type '(choice
          (number :tag "Maximum of buffers allowed")
          (const :tag "Disable cleanup" nil))
  :group 'deadgrep)
```

**Comment by fleimgruber** [comment]
@firstrow this helped as it led me to the actual issue here: It could not possibly work the way I imagined it, because as soon as the search term changes, the deadgrep buffer name changes as well. The buffer name is constructed as `*deadgrep <search-term> <directory>*` so of course it will re-create a new buffer and show it in another window, because the buffer name changed. It works as I expected initially if I use the same search term in the same directory, i.e. buffer and window are re-used. @Wilfred do you see any other way to accomplish that behavior?
