### ISSUE TITLE
How to search filename with pattern?

### ISSUE THREAD

**Issue by LiuYinCarl** [Wilfred/deadgrep#122]
deadgrep is a perfect tool to search content in a project with fast speed. Today, I want to use deadgrep to search file in project, but deadgrep seems not support it. 

In terminal, I use ripgrep to search files which's name fit a pattern, such as below

```bash
$:~/github/cpython$ rg --files | rg "pycore_p"
Include/internal/pycore_parser.h
Include/internal/pycore_pyarena.h
Include/internal/pycore_pyhash.h
Include/internal/pycore_pathconfig.h
Include/internal/pycore_pyerrors.h
Include/internal/pycore_pylifecycle.h
Include/internal/pycore_pymem.h
Include/internal/pycore_pystate.h
```

I would like to know if there a way to implement the search effect using deadgrep.

thanks.

**Comment by LiuYinCarl** [comment]
I found a package named `fzf.el` can do file name search, no need deadgrep to solve the problem. So I'l close the issue.

**Comment by terlar** [comment]
This might also be of interest:
https://github.com/muffinmad/emacs-find-file-rg
