### ISSUE TITLE
file-remote-p: Wrong type argument: stringp, (Git "~/.emacs.d/")

### ISSUE THREAD

**Issue by starenka** [Wilfred/deadgrep#123]
got this while searching `M-x deadgrep` in dir with git repo... unfortunatelly `toggle-debug-on-error` won't spawn on this, so i can't provide any more info :/

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0) of 2021-11-27, modified by Debian
deadgrep 0.10

**Comment by starenka** [comment]
sorry, it is working while using `melpa` (not `melpa-stable`) version

**Comment by Wilfred** [comment]
I've tagged a new release so melpa-stable has a newer version :)
