### ISSUE TITLE
[Question] Is the search in directory recursive?

### ISSUE THREAD

**Issue by ChloeZhou1997** [Wilfred/deadgrep#126]
Hi, I am new to emacs and don't know much about the package deadgrep is built upon, I am wondering if I am searching in directory `~/notes`, and there are contents in the subdirectory `~/notes/roamnotes`, will the search also recursively search inside of those subdirectory?

**Comment by Wilfred** [comment]
Yep, `rg` recurses into subdirectories. By default it recurses into all directories, but it ignores any directories mentioned in `.gitignore` or `.ignore` :)
