### ISSUE TITLE
(optionally) prompt for root search directory

### ISSUE THREAD

**Issue by flub** [Wilfred/deadgrep#14]
Thanks for deadgrep!

I often know I want to limit the search to a subtree of the (very large) auto-detected project root.  Currently I can only do this by starting the search and then changing the directory, racing ripgrep who's currently busy reading lots of unneeded disk and loading it into the disk cache.

It would be nice if after invoking M-x deadgrep I got a second prompt for the search root directory, with the current auto-detected one pre-filled.  I appreciate this is an extra keystroke for the current case, so it could also be a customize option to toggle this behaviour or not.

Do you think this is worth doing or is it too niche?

**Comment by flub** [comment]
That seems like it could also be nice.  Less generalisable though,
e.g. with a customize option it could be extended to be a list of things
to prompt for.  But I guess sometimes one likes to be prompted and
sometimes one doesn't, for which a prefix is nice.

**Comment by Wilfred** [comment]
The problem is knowing which options are worth allowing users to prompt for. Do we provide a distinct keybinding for each possible setting you can prompt for? What about prompting for multiple options?

I'm open to suggestions, but I can't see an obvious UI that suits this case.

**Comment by iquiw** [comment]
I was thinking to open the same request.

My initial thought is that prefix arg prompts search directory, but `without starting the search` is fine for me.

**Comment by flub** [comment]
Agreed, a generic UI is complicated and fickle.  So I guess the
prefix-arg to not start the search is a good solution.

**Comment by Wilfred** [comment]
OK, `C-u M-x deadgrep` now disables the automatic starting of a search. Please have a play with it and tell me what you think.

**Comment by iquiw** [comment]
@Wilfred It does meet my need. Thank you!

**Comment by flub** [comment]
I initially ran into #26 when trying this out but by the time I got round to investigate this a little more it was already fixed!  Thanks @Wilfred and @iquiw !

**Comment by Patrick-T-Anderson** [comment]
Is there a way to make deadgrep always choose the current-working-directory as the directory to search.
I don't see how this could ever be wrong.

**Comment by Wilfred** [comment]
@Patrick-T-Anderson something like this should do the trick:

```lisp
(defun wh/return-default-dir ()
  default-directory)

(setq deadgrep-project-root-function #'wh/return-default-dir)
```

**Comment by Patrick-T-Anderson** [comment]
Thanks @Wilfred
