### ISSUE TITLE
Exclude glob patterns not working

### ISSUE THREAD

**Issue by jokem59** [Wilfred/deadgrep#142]
Output of `deadgrep-debug`
```
About your environment:
Platform: gnu/linux
Emacs version: 27.1.91
Command: rg --no-config --color=ansi --line-number --no-heading --no-column --with-filename --fixed-strings --word-regexp --smart-case --type-add=custom:!gtest* --type=custom -- wonder_wall
default-directory: "~/dev/MyProject"
exec-path: ("~/.cargo/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin")

Initial output from ripgrep:
nil

Please file bugs at https://github.com/Wilfred/deadgrep/issues/new
```
   - Also tried with `--type-add=custom:'!gtest*'`

deadgrep version: `20230914.206`

I can't seem to find a way to exclude file patterns from deadgrep searching.  Taking a look at the debug output, glob patterns are passed into the `--type-add` argument, and that custom type used for glob purposes.

From my testing, `--type-add` works for matching globs, but doesn't support EXCLUDING globs
  - `--type-add=custom:'gtest*'` ->  Works
  - `--type-add=custom:'!gtest*'` -> Doesn't work

Perhaps `glob` options should pass straight into `-g, --glob` parameter?

**Comment by jokem59** [comment]
This change causes exclude globs to work properly while preserving the behaving of include globs:

```
diff --git a/deadgrep.el b/deadgrep.el
index 3fc6b8c..e74cfca 100644
--- a/deadgrep.el
+++ b/deadgrep.el
@@ -721,7 +721,8 @@ to obtain ripgrep results."
      ((eq (car-safe deadgrep--file-type) 'type)
       (push (format "--type=%s" (cdr deadgrep--file-type)) args))
      ((eq (car-safe deadgrep--file-type) 'glob)
-      (push (format "--glob=%s" (cdr deadgrep--file-type)) args))
+      (push (format "--type-add=custom:%s" (cdr deadgrep--file-type)) args)
+      (push "--type=custom" args))
      (t
       (error "Unknown file-type: %S" deadgrep--file-type)))

```

**Comment by jokem59** [comment]
Pull Request: https://github.com/Wilfred/deadgrep/pull/143

**Comment by Wilfred** [comment]
Merged the PR, I don't think there's anything else to do here.
