### ISSUE TITLE
deadgrep not using current dired folder as search directory

### ISSUE THREAD

**Issue by vnckppl** [Wilfred/deadgrep#145]
deadgrep no longer searches the underlying folder in dired, but always defaults to searching the home directory. This also happens with emacs -Q:

```
(add-to-list 'load-path "/home/vincent/.emacs.d/elpa/deadgrep-20231130.1628")
(add-to-list 'load-path "/home/vincent/.emacs.d/elpa/s-20220902.1511")
(add-to-list 'load-path "/home/vincent/.emacs.d/elpa/dash-20240103.1301")
(add-to-list 'load-path "/home/vincent/.emacs.d/elpa/spinner-1.7.4")

(require 's)
(require 'dash)
(require 'spinner)
(require 'deadgrep)
```

and then running M-x deadgrep. Has this behavior changed?

Deadgrep debug output:

```
Platform: gnu/linux
Emacs version: 29.1.50
Command: rg --no-config --color=ansi --line-number --no-heading --no-column --with-filename --fixed-strings --smart-case -- test .
default-directory: "~/"
```

Ripgrep version:

`ripgrep 13.0.0`

**Comment by brongulus** [comment]
Seeing the same behaviour.

**Comment by Wilfred** [comment]
Hmm, this is a difficult tradeoff to choose a good default. Note that you can call deadgrep with a prefix to change the search directory before running, or you can override `deadgrep-project-root-function` to change how deadgrep decides the root directory to start the search from.

Given that this can be overridden, I'm going to close, but I'm open to suggestions of improvements here.

**Comment by brongulus** [comment]
Invoking deadgreap with prefix-argument like `C-u M-x deadgrep` only prompts for the search term and not the search directory. Am I doing something wrong?
