### ISSUE TITLE
Populate errors list for (next-error) and (previous-error)

### ISSUE THREAD

**Issue by cjohansson** [Wilfred/deadgrep#15]
It would nice to be able to use `M-g n` and `M-g p` for `(next-error)` and `(previous-error)` like it's possible with `rgrep` and `grep`

**Comment by Wilfred** [comment]
Hmm, we could do something like this:

```
(define-key deadgrep-mode-map [remap next-error] #'deadgrep-forward)
(define-key deadgrep-mode-map [remap previous-error] #'deadgrep-backward)
```

but that doesn't help users who explicitly do `next-error` and `previous-error`. It feels slightly dishonest to support `next-error` (search results aren't errors), but as you say `rgrep` and `grep` do exactly this.

What would suit your workflow? Do you use the keybindings or the commands themselves?

**Comment by Wilfred** [comment]
Turns out there's `next-error-function`, so this should work properly now :)
