### ISSUE TITLE
why not rg.el?

### ISSUE THREAD

**Issue by kidd** [Wilfred/deadgrep#2]
Hi Wilfred,
Just wanted to note that rg.el has many hidden niceties like grouping (`rg-group-result`), search the current word in the current project for files like the curent one (`rg-dwim`) and is also compatible with wgrep.

Not to deter you from deadgrep (Wilfredware is proved to always have an edge), but maybe trying to add to rg instead of of creating your own wheel.....

I recently discovered that `m-?` is bound to `xref-find-definitions` in many modes, that is intended to cover yet the same use case. It doesn't use compile-mode but its own `xref--xref-buffer-mode`.

Just my 2c on that :)

**Comment by Wilfred** [comment]
Thanks for the feedback!

Yeah, I'm a big fan of `rg-dwim`, it's a really helpful command in many circumstances. I will update ALTERNATIVES to mention this (and the other features you mention).

I'm not trying to say "mine is the best", rather "I've looked at the alternatives so I think my decision to write a separate tool is justified". I will try to tweak the wording to reflect my admiration of these other projects :)

The main difference with deadgrep is that it's not built on `compilation-mode` and so I can completely control what the output looks like, much like magit.

Regarding wgrep, I've always found it a little awkward to use (you have to save twice IIRC), so I think deadgrep could do something a little easier to use.

**Comment by kidd** [comment]
No problem on the wording or anything whatsoever, I just wanted to share those alternatives in case you didn't know about them :)

Cheers!
