### ISSUE TITLE
Tramp support

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/deadgrep#21]
Support running on a remote host if rg is installed there.

**Comment by iquiw** [comment]
I think it is sufficient to change `start-process-shell-command` to `start-file-process-shell-command` for basic Tramp support.

In case of different OS's used on local and remote, something like `deadgrep-remote-executable`  may be required (Default to "rg").

**Comment by Wilfred** [comment]
Wow, that seems to be all that I need! Thank you :)

**Comment by iquiw** [comment]
@Wilfred Sorry, I forgot to mention I found one more change required after writing the above comment.

`shell-command-to-string` (in `deadgrep--type-list`) also does not work with Tramp as it uses `shell-file-name` which is platform dependent. I suppose the following works instead.

```emacs-lisp
(with-output-to-string
  (with-current-buffer standard-output
    (process-file-shell-command
     (format "%s --type-list" deadgrep-executable)
     nil '(t nil))))
```

**Comment by iquiw** [comment]
Sent PR https://github.com/Wilfred/deadgrep/pull/35

**Comment by Wilfred** [comment]
Fixed :)

**Comment by iquiw** [comment]
FYI: `shell-command-to-string` was fixed to work with Tramp in `master` (not yet released)

https://lists.gnu.org/archive/html/emacs-devel/2018-01/msg00726.html
