### ISSUE TITLE
always use deadgrep-executable

### ISSUE THREAD

**Issue by gizmomogwai** [Wilfred/deadgrep#23]
first of all, i really love this ui to ripgrep! thanks for that.

there is still a rg %s in the source, so it's not working for me. please always use deadgrep-executable.

**Comment by Wilfred** [comment]
I can't see anywhere where we don't use `deadgrep-executable`.

I know there's this line in the code:

```emacs-lisp
(start-process-shell-command
           (format "rg %s" search-term)
           (current-buffer)
           command)
```

But the first argument to `start-process-shell-command` is just the name of the process.

How is deadgrep not working?

**Comment by gizmomogwai** [comment]
thanks for the answer... you are right .. i did have a problem with ripgrep being in the wrong path, after correcting that, deadgrep-executable was not reevaluated, so it just did not find rg at all. after emacs restart everything works great! sorry for the bad bug report!
