### ISSUE TITLE
[Feature Request] ability to loop through search hits

### ISSUE THREAD

**Issue by ananthakumaran** [Wilfred/deadgrep#28]
full-ack.el provides this functionality and it makes it really easy to do repo wide refactor

1) make a search
2) jump to first hit in the search result buffer
3) start to record a macro <kbd>C-x (</kbd>
4) Press enter (this will take you to the file and put the cursor at the start of the match)
5) do the refactoring
6) jump back to the search result buffer
7) move to the nex hit
8) finish the macro <kbd>C-x (</kbd>

The macro can now be applied for the rest of the hits using <kbd>C-x e</kbd>. The important functionality that makes this possible is the ability to move to the **start** of next search hit.

**Comment by Wilfred** [comment]
Does `next-error` meet your needs?

**Comment by Wilfred** [comment]
OK, I've added commands `deadegrep-forward-match` and `deadgrep-backward-match`. I think they should meet your needs, but let me know if not :)
