### ISSUE TITLE
Messy search output

### ISSUE THREAD

**Issue by manuel-uberti** [Wilfred/deadgrep#3]
I ran `deadgrep` looking for `use-package` in my `.emacs.d`, but results are hard to read.

I think a picture describes it better.

![shot](https://user-images.githubusercontent.com/8199224/41700879-7848f0ba-752a-11e8-904a-9e9faa785f68.png)

This is how I configured `deadgrep`:
```
(use-package deadgrep
  :load-path "~/githubs/deadgrep"
  :bind ("<f7>" . deadgrep))
```
And these are some details about my system:
```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2018-06-20

Repository revision: 3a47f3921bdaaf7b7d80dc3be05a5f1b1f2501eb
Configured using:
--host=x86_64-debian-linux-gnu

Emacs uptime: 3 minutes, 53 seconds
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.1
```

**Comment by Wilfred** [comment]
Thanks, I believe I've fixed the issue now.

**Comment by manuel-uberti** [comment]
Thanks, it works now.
