### ISSUE TITLE
zsh:1: command not found: nil

### ISSUE THREAD

**Issue by lnguyen46** [Wilfred/deadgrep#40]
![screen shot 2018-12-30 at 20 34 57](https://user-images.githubusercontent.com/22726858/50547757-04a1dd80-0c73-11e9-8a3b-a0cbc3e52ecc.png)

deadgrep version on my machine is `deadgrep-20181229.1348`

**Comment by lnguyen46** [comment]
The value is `nil`

**Comment by Wilfred** [comment]
Try setting `deadgrep-executable` to `"rg"`? Looks like `(executable-find "rg")` didn't find anything when deadgrep.el was loaded.

**Comment by lnguyen46** [comment]
Yes. Run `(setq deadgrep-executable "rg")` solved the problem.

**Comment by hajovonta** [comment]
Hi,
I had the same problem, I found the package in MELPA and installed it via package-install. After trying, I tried to configure it via customize. :) I recommend putting the deadgrep-executable option in customize.

**Comment by Wilfred** [comment]
That's a great suggestion! I've added it to customize.
