### ISSUE TITLE
Use 'words as default search type instead of 'string

### ISSUE THREAD

**Issue by thermopyle** [Wilfred/deadgrep#46]
Right now I think 'string is used as default search type. Is it possible to set this to 'words instead?

**Comment by Wilfred** [comment]
As soon as you switch once, it should 'stick' for future searches. Alternatively, the following should work:

```
(setq-default deadgrep--search-type 'words)
```

Although this is an internal setting, so in principle it could change. I don't anticipate any changes though :)
