### ISSUE TITLE
Doesn't work on Windows?

### ISSUE THREAD

**Issue by andschwa** [Wilfred/deadgrep#5]
I have `counsel-rg` and `rg.el` working just fine on Windows (so `rg` can be found blah blah), but `deadgrep` is just sitting, spinning, never-ending, with no results. Anyone else test it on Windows?

**Comment by Wilfred** [comment]
Do you get any error output? What's the output of `(executable-find "rg")`?

**Comment by mookid** [comment]
Can reproduce. `(executable-find "rg")` yields `"c:/ProgramData/chocolatey/bin/rg.exe"`

neither `deadgrep--process-filter` or `deadgrep--process-sentinel` seem to be called, unless I kill the process.
