### ISSUE TITLE
Python files suggest yacc rather than py as the type

### ISSUE THREAD

**Issue by Schnouki** [Wilfred/deadgrep#56]
I'm using the latest version of deadgrep available on MELPA, and ripgrep 11.0.1. Emacs 26.2, Arch Linux.

```elisp
(deadgrep--relevant-file-type "foobar.py" (deadgrep--type-list)) ;; yacc: *.y
(deadgrep--relevant-file-type "foobar.pyi" (deadgrep--type-list)) ;; swig: *.i
```

Looks like the heuristic can be improved further: `.py` has one exact match so it should be preferred over `.y`...

In fact this looks like `deadgrep--matches-globs-p` doesn't work correctly and treats the `.` as in a regexp instead of a glob:

```elisp
(-filter (-lambda ((_type globs))
	   (deadgrep--matches-globs-p "foobar.py" globs))
	 (deadgrep--type-list))
;; result: (("py" ("*.py")) ("yacc" ("*.y")))
```

**Comment by Wilfred** [comment]
Thanks for the clear bug report :)

**Comment by Schnouki** [comment]
Thanks for the super quick fix! :)
