### ISSUE TITLE
Run in `default-directory` if no git/project/projectile root found

### ISSUE THREAD

**Issue by PhilHudson** [Wilfred/deadgrep#62]
... and/or private a `C-u C-u` prefix arg for selecting cwd, with history

**Comment by Wilfred** [comment]
It's already the case that `default-directory` is used when there's no project directory found. Could you clarify?

**Comment by PhilHudson** [comment]
You are correct. I had an erroneous value in my `default-directory`.
Sorry for the noise. Please close.

On 02/10/2019, Wilfred Hughes <notifications@github.com> wrote:
> It's already the case that `default-directory` is used when there's no
> project directory found. Could you clarify?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Wilfred/deadgrep/issues/62#issuecomment-537272750


-- 
phil.hudson@iname.com                      PGP/GnuPG ID: 0x887DCA63

**Comment by rien333** [comment]
I run emacs as a server, so my `default-directory` is _always_ `~/`. Any work around? It would be really neat if I could tell deadgrep where to look, because now deadgrep basically always starts searching from my homefolder.

**Comment by Wilfred** [comment]
`default-directory` is a buffer-local variable, so it should depend on the buffer you start the search from. Could you give an example of how to reproduce your issue?

**Comment by rien333** [comment]
> default-directory is a buffer-local variable, so it should depend on the buffer you start the search from. Could you give an example of how to reproduce your issue?

This seems to work fine now, sorry for the misinformation (no idea what happened, I rarely touch my config anymore).

That said, somtimes `deadgrep` still searches not in `default-directory`, but in `~` . `default-directory` always has the value you would expect, but in some folders (but not others, strangely enough) `deadgrep` nevertheless searches in `~`. So it works in `~/foo/bar`, but not in `~/xyz`, eventhough  `default-directory` is set correctly in both cases.
