### ISSUE TITLE
Suggestion: don't include the search term in the buffer name if it's too long

### ISSUE THREAD

**Issue by j-cr** [Wilfred/deadgrep#71]
Currently with a long search term the progress indicator in the deadgrep buffer is not visible, since all the space in the mode line is taken by the buffer name which includes the full search string. 

![Screenshot-short](https://user-images.githubusercontent.com/41063058/72212354-1b247b00-34fc-11ea-89da-61604ca0a029.png)
![Screenshot-long](https://user-images.githubusercontent.com/41063058/72212353-1a8be480-34fc-11ea-92dc-58f5702ddefa.png)

**Comment by Wilfred** [comment]
That's a great idea, thanks :)
