### ISSUE TITLE
Show results based on proximity to current buffer

### ISSUE THREAD

**Issue by hisnawi** [Wilfred/deadgrep#72]
This is more of an enhancement.
If it is possible to show search results starting with (current file) followed by (current directory) and finally the rest of the results from the other files in the repo.
That would cut so much time when searching.

**Comment by Wilfred** [comment]
Sorry, but I don't think this is feasible.

deadgrep shows results in the order that ripgrep outputs them. Any other form of ordering requires us to reorder results as they arrive, which increases implementation complexity, might be surprising for the user, and can also be slower.

If you can see a nice way to do this I'm not necessarily opposed, but I can't see any good approaches.
