### ISSUE TITLE
Allow searching in other directories

### ISSUE THREAD

**Issue by joca-bt** [Wilfred/deadgrep#92]
I've used ag.el for a long time and I'm now trying rg with deadgrep. I work in a massive repo and most of the time I'm only grepping in subdirectories and not in the entire repo. deadgrep search the entire VCS by default.

I think allowing searching in specific folders when working in a VCS makes sense.

**Comment by terlar** [comment]
You can select a specific directory to search with deadgrep, you can see it in the deadgrep buffer.

**Comment by joca-bt** [comment]
Yes, but not on the initial `M-x deadgrep`. I need to have the buffer open and re-search.

**Comment by Wilfred** [comment]
@joca-bt have you tried `C-u M-x deadgrep` to open the buffer without starting a search? Also, you might find `deadgrep-project-root-overrides` handy.

**Comment by marcora** [comment]
I would love to have a function to start deadgrep in a directory passed as a argument.

**Comment by cpitclaudel** [comment]
@Wilfred I moved from `ag` to `ripgrep` and I was happy to see that there was a package for it made by you :) (I like `ag.el` a lot).

The `deadgrep` experience is much better in some ways, but not being able to select the directory to search is a limitation.  `C-u M-x deadgrep` doesn't really help: it requires a moving the point to the "directory" line, which is pretty inefficient compared to the experience I had in your `ag` package.

At first I thought it was a matter of getting used to the smart project root detection, but after about a month I find that I need to edit the directory more often than not, and the interface for that in your `ag` package is much more efficient, so I've moved back to that.  Any chance of porting that same interface to deadgrep? :)

Thanks for your work.

**Comment by fd3kyt** [comment]
A temporary solution using prefix arg:

```elisp
(defun my-deadgrep (search-term dir)
  "Search for SEARCH-TERM in DIR.

Prefix arg:
None: use `deadgrep-project-root-function' (default).
\\[negative-argument]: choose a directory.
C-0: current directory.
\\[universal-argument]: see `deadgrep'."
  (interactive (let ((search-term (deadgrep--read-search-term)))
                 (list search-term
                       (cond
                        ((eq current-prefix-arg 0)
                         (setq current-prefix-arg nil)
                         default-directory)
                        ((eq current-prefix-arg '-)
                         (setq current-prefix-arg nil)
                         (read-directory-name
                          (format  "Search for \"%s\" in: " search-term)
                          nil nil t))))))
  (let ((deadgrep-project-root-function (if dir
                                            (lambda () dir)
                                          deadgrep-project-root-function)))
    (deadgrep search-term)))
```

**Comment by To1ne** [comment]
Adapted @fd3kyt's function now #101 is merged.

```elisp
(defun my-deadgrep (search-term dir)
  "Search for SEARCH-TERM in DIR.

Prefix arg:
None: use `deadgrep-project-root-function' (default).
\\[negative-argument]: choose a directory.
C-0: current directory.
\\[universal-argument]: see `deadgrep'."
  (interactive (let ((search-term (deadgrep--read-search-term)))
                 (list search-term
                       (cond
                        ((eq current-prefix-arg 0)
                         (setq current-prefix-arg nil)
                         default-directory)
                        ((eq current-prefix-arg '-)
                         (setq current-prefix-arg nil)
                         (read-directory-name
                          (format  "Search for \"%s\" in: " search-term)
                          nil nil t))
                        (t nil)))))
    (deadgrep search-term dir))
```
